### ISSUE TITLE
Enable comonad by default

### ISSUE THREAD

**Issue by typesanitizer** [theindigamer/edit#1]
/u/phadej on Reddit pointed out that comonad is a light dependency and should be enabled by default. I was under the wrong impression that it was actually a heavy dependency (I think I somehow confused it with `kan-extensions`?).

Similarly, I think QuickCheck should also be enabled by default. If a user wants a different arbitrary instance, they can use a newtype wrapper.

**Comment by typesanitizer** [comment]
@phadej thanks for the suggestion. Took me a while to fix it (my excuse: cabal acting up, so I upgraded it). This has been fixed in the new release.

**Comment by phadej** [comment]
Great, thanks!
